// Package certs writes custom TLS material for Traefik's file provider.
// The agent stores PEM files on disk; Traefik watches a dynamic YAML that
// lists them. Paths inside the YAML use the container mount (/certs/…).
package certs

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// Default container paths Traefik sees (must match docker-compose mounts).
const (
	ContainerCertsDir = "/certs"
)

var safeHost = regexp.MustCompile(`[^a-zA-Z0-9._-]+`)

// Manager writes host cert/key PEMs and regenerates Traefik dynamic config.
type Manager struct {
	// HostDirs are where the agent writes files (bind-mounted into Traefik).
	CertsDir   string
	DynamicDir string
	// CertsMount is the path prefix Traefik uses inside the container.
	CertsMount string
}

func New(certsDir, dynamicDir string) *Manager {
	return &Manager{
		CertsDir:   certsDir,
		DynamicDir: dynamicDir,
		CertsMount: ContainerCertsDir,
	}
}

func sanitizeHost(host string) string {
	h := strings.ToLower(strings.TrimSpace(host))
	h = safeHost.ReplaceAllString(h, "_")
	if h == "" {
		return "unknown"
	}
	return h
}

func (m *Manager) certPath(host string) string {
	base := sanitizeHost(host)
	return filepath.Join(m.CertsDir, base+".crt")
}

func (m *Manager) keyPath(host string) string {
	base := sanitizeHost(host)
	return filepath.Join(m.CertsDir, base+".key")
}

func (m *Manager) containerCert(host string) string {
	base := sanitizeHost(host)
	return m.CertsMount + "/" + base + ".crt"
}

func (m *Manager) containerKey(host string) string {
	base := sanitizeHost(host)
	return m.CertsMount + "/" + base + ".key"
}

// Put writes cert+key for host and refreshes the Traefik file-provider YAML.
func (m *Manager) Put(host, certPEM, keyPEM string) error {
	if strings.TrimSpace(host) == "" {
		return fmt.Errorf("host is required")
	}
	if !strings.Contains(certPEM, "BEGIN CERTIFICATE") {
		return fmt.Errorf("certPEM does not look like a PEM certificate")
	}
	if !strings.Contains(keyPEM, "BEGIN") || !strings.Contains(keyPEM, "PRIVATE KEY") {
		return fmt.Errorf("keyPEM does not look like a PEM private key")
	}
	if err := os.MkdirAll(m.CertsDir, 0o700); err != nil {
		return err
	}
	if err := os.MkdirAll(m.DynamicDir, 0o700); err != nil {
		return err
	}
	if err := os.WriteFile(m.certPath(host), []byte(certPEM), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(m.keyPath(host), []byte(keyPEM), 0o600); err != nil {
		return err
	}
	return m.rewriteDynamic()
}

// Delete removes cert+key for host (if present) and refreshes dynamic config.
func (m *Manager) Delete(host string) error {
	_ = os.Remove(m.certPath(host))
	_ = os.Remove(m.keyPath(host))
	return m.rewriteDynamic()
}

// ListHosts returns hosts that currently have both cert and key on disk.
func (m *Manager) ListHosts() ([]string, error) {
	entries, err := os.ReadDir(m.CertsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	keys := map[string]bool{}
	certs := map[string]bool{}
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		switch {
		case strings.HasSuffix(name, ".crt"):
			certs[strings.TrimSuffix(name, ".crt")] = true
		case strings.HasSuffix(name, ".key"):
			keys[strings.TrimSuffix(name, ".key")] = true
		}
	}
	var hosts []string
	for base := range certs {
		if keys[base] {
			hosts = append(hosts, base)
		}
	}
	sort.Strings(hosts)
	return hosts, nil
}

func (m *Manager) rewriteDynamic() error {
	if err := os.MkdirAll(m.DynamicDir, 0o700); err != nil {
		return err
	}
	hosts, err := m.ListHosts()
	if err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# Generated by selfhosted-agent — do not edit.\n")
	b.WriteString("tls:\n")
	if len(hosts) == 0 {
		b.WriteString("  certificates: []\n")
	} else {
		b.WriteString("  certificates:\n")
		for _, h := range hosts {
			fmt.Fprintf(&b, "    - certFile: %s\n", m.containerCert(h))
			fmt.Fprintf(&b, "      keyFile: %s\n", m.containerKey(h))
		}
	}
	path := filepath.Join(m.DynamicDir, "certs.yml")
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}
